# Generated by Django 5.2.8 on 2025-12-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('ecole', '🏫 École et Scolarité'), ('alimentation', '🍽️ Alimentation et Repas'), ('sommeil', '😴 Sommeil et Routines'), ('jeux', '🎮 Jeux et Activités'), ('sante', '💊 Santé et Thérapies'), ('entraide', '🤝 Entraide et Soutien'), ('libre', '💬 Discussions Libres')], default='libre', max_length=20),
        ),
    ]
