# Generated by Django 6.0 on 2025-12-07 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Garçon'), ('F', 'Fille'), ('A', 'Autre')], default='M', max_length=1)),
                ('niveau_autonomie', models.CharField(choices=[('faible', 'Faible autonomie'), ('moyen', 'Autonomie moyenne'), ('eleve', 'Autonomie élevée')], default='moyen', max_length=20)),
                ('besoins_specifiques', models.TextField(blank=True, help_text='Sensibilités, préférences, particularités...', null=True)),
                ('couleur_preferee', models.CharField(blank=True, max_length=50, null=True)),
                ('activites_preferees', models.TextField(blank=True, help_text='Jeux, activités favorites...', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enfants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'ordering': ['-created_at'],
            },
        ),
    ]
