# Generated by Django 6.0 on 2025-12-10 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_enfant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilEducateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('specialite', models.CharField(help_text='Ex: Autisme, Troubles du langage, etc.', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='educateurs/')),
                ('etablissement', models.CharField(blank=True, max_length=200)),
                ('annees_experience', models.IntegerField(default=0)),
                ('certifications', models.TextField(blank=True, help_text='Liste des certifications')),
                ('bio', models.TextField(help_text="Présentation de l'éducateur")),
                ('methodologie', models.TextField(blank=True, help_text='Approches pédagogiques utilisées')),
                ('nombre_enfants', models.IntegerField(default=0, help_text="Nombre d'enfants suivis")),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_educateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Éducateur',
                'verbose_name_plural': 'Profils Éducateurs',
                'ordering': ['-note_moyenne', '-nombre_enfants'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('educateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoignages', to='authen.profileducateur')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'ordering': ['-date'],
            },
        ),
    ]
