# Generated by Django 5.2.8 on 2025-12-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_enfant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
