# Generated by Django 5.2.8 on 2025-12-09 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_alter_enfant_id_alter_userprofile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nouveau_parent', '🌟 Nouveau Parent'), ('premier_pas', '✍️ Premier Pas'), ('parent_engage', '💬 Parent Engagé'), ('parent_aidant', '❤️ Parent Aidant'), ('pilier', '🎖️ Pilier de la Communauté'), ('mentor', '🤝 Mentor'), ('famille', '👪 Famille ComAutis')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reaction', '❤️ Réaction'), ('comment', '💬 Commentaire'), ('badge', '🎉 Badge'), ('mention', '📢 Mention')], max_length=20)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge Utilisateur',
                'verbose_name_plural': 'Badges Utilisateurs',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
