# Generated by Django 6.0 on 2025-12-12 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_badge_notification_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu', models.CharField(choices=[('memory', '🧠 Memory'), ('compter_3', "🔢 Compter jusqu'à 3"), ('compter_10', "🔢 Compter jusqu'à 10"), ('couleurs', '🎨 Apprendre les Couleurs'), ('emotions', '😊 Reconnaître les Émotions'), ('memory_fruits', '🍎 Memory Fruits'), ('jours_semaine', '📅 Jours de la Semaine'), ('animaux', '🐶 Cris des Animaux'), ('fruits', '🍓 Apprendre les Fruits'), ('memory_couleurs', '🌈 Memory Couleurs'), ('saisons', '🍂 Les Saisons'), ('puzzle', '🧩 Puzzle'), ('labyrinthe', '🎯 Labyrinthe'), ('pictogrammes', '📊 Pictogrammes'), ('dessiner', '✏️ Dessiner'), ('videos', '🎥 Vidéos'), ('histoires', '📖 Histoires')], max_length=50)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(default=0, help_text='Durée en minutes')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('reussi', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='authen.enfant')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_debut'],
            },
        ),
    ]
