# Generated by Django 6.0 on 2025-12-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_messageeducateur'),
        ('progression', '0002_alter_enfantprogression_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileducateur',
            name='enfants_suivis',
            field=models.ManyToManyField(blank=True, related_name='educateurs', to='progression.enfantprogression'),
        ),
    ]
