# Generated by Django 6.0 on 2025-12-12 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_alter_badge_id_alter_enfant_id_alter_notification_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_email', models.BooleanField(default=True)),
                ('rappels_routine', models.BooleanField(default=True)),
                ('alertes_forum', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('clair', 'Mode clair'), ('sombre', 'Mode sombre'), ('auto', 'Automatique')], default='clair', max_length=10)),
                ('taille_police', models.CharField(choices=[('petite', 'Petite'), ('normale', 'Normale'), ('grande', 'Grande'), ('tres_grande', 'Très grande')], default='normale', max_length=15)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=5)),
                ('contraste_eleve', models.BooleanField(default=False)),
                ('sons_jeux', models.BooleanField(default=True)),
                ('musique_fond', models.BooleanField(default=False)),
                ('volume', models.CharField(choices=[('silencieux', 'Silencieux'), ('faible', 'Faible'), ('moyen', 'Moyen'), ('fort', 'Fort')], default='moyen', max_length=15)),
                ('lecture_vocale', models.BooleanField(default=False)),
                ('visibilite_profil', models.CharField(choices=[('tous', 'Tous les membres'), ('amis', 'Amis uniquement'), ('prive', 'Privé')], default='tous', max_length=10)),
                ('partage_donnees', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
            },
        ),
    ]
