# Generated by Django 5.2.8 on 2025-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
