# Generated by Django 6.0 on 2025-12-14 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducateurEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('notes_privees', models.TextField(blank=True, help_text="Notes privées de l'éducateur", null=True)),
                ('objectifs', models.TextField(blank=True, help_text='Objectifs fixés pour cet enfant', null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('educateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants_suivis', to=settings.AUTH_USER_MODEL)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educateurs', to='authen.enfant')),
            ],
            options={
                'verbose_name': 'Éducateur-Enfant',
                'verbose_name_plural': 'Éducateurs-Enfants',
                'ordering': ['-date_ajout'],
                'unique_together': {('educateur', 'enfant')},
            },
        ),
        migrations.CreateModel(
            name='ObservationEducateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_observation', models.CharField(choices=[('progres', '📈 Progrès'), ('difficulte', '⚠️ Difficulté'), ('comportement', '😊 Comportement'), ('reussite', '🎉 Réussite'), ('autre', '📝 Autre')], default='autre', max_length=20)),
                ('visible_parent', models.BooleanField(default=True, help_text='Le parent peut-il voir cette observation ?')),
                ('educateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='authen.enfant')),
            ],
            options={
                'verbose_name': 'Observation Éducateur',
                'verbose_name_plural': 'Observations Éducateur',
                'ordering': ['-date_observation'],
            },
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
