# Generated by Django 6.0 on 2025-12-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_educateurenfant_observationeducateur_and_more'),
        ('authen', '0007_userprofile_photo_profil'),
    ]

    operations = [
    ]
