# Generated by Django 5.2.8 on 2025-12-13 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_alter_level_id_alter_subscription_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JeuPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu_code', models.CharField(choices=[('memory', '🧠 Memory'), ('compter_10', "🔢 Compter jusqu'à 10"), ('puzzle', '🧩 Puzzle'), ('labyrinthe', '🌀 Labyrinthe'), ('saisons', '🌻 Les Saisons')], help_text='Code unique du jeu', max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, default=4.99, max_digits=6)),
                ('icone', models.CharField(default='🎮', max_length=10)),
                ('actif', models.BooleanField(default=True, help_text='Jeu disponible à la vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jeu Premium',
                'verbose_name_plural': 'Jeux Premium',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PaiementJeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('numero_carte_masque', models.CharField(blank=True, help_text='Ex: **** **** **** 1234', max_length=19)),
                ('nom_carte', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('jeu_premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiement.jeupremium')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_jeux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement Jeu',
                'verbose_name_plural': 'Paiements Jeux',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='AccesJeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeux_debloques', to=settings.AUTH_USER_MODEL)),
                ('jeu_premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiement.jeupremium')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiement.paiementjeu')),
            ],
            options={
                'verbose_name': 'Accès Jeu Premium',
                'verbose_name_plural': 'Accès Jeux Premium',
                'ordering': ['-date_achat'],
                'unique_together': {('parent', 'jeu_premium')},
            },
        ),
    ]
