# Generated by Django 6.0 on 2025-12-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnfantProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enfant', models.CharField(max_length=100)),
                ('niveau', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('activites_terminees', models.IntegerField(default=0)),
                ('activites_totales', models.IntegerField(default=10)),
            ],
        ),
    ]
