# Generated by Django 6.0 on 2025-12-09 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfantprogression',
            options={'verbose_name': 'Enfant progression', 'verbose_name_plural': 'Enfant progressions'},
        ),
        migrations.AddField(
            model_name='enfantprogression',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantprogression',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
