# Generated by Django 6.0 on 2025-12-10 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0002_alter_enfantprogression_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(help_text="Emoji ou nom d'icône", max_length=50)),
                ('condition_type', models.CharField(choices=[('niveau', 'Atteindre un niveau'), ('score', 'Atteindre un score total'), ('activites', "Nombre d'activités terminées"), ('jours_consecutifs', "Jours d'activité consécutifs"), ('type_activite', "Nombre d'activités d'un type spécifique")], max_length=50)),
                ('condition_valeur', models.IntegerField(help_text='Valeur à atteindre pour obtenir le badge')),
                ('condition_details', models.CharField(blank=True, help_text="Détails supplémentaires (ex: type d'activité)", max_length=100)),
                ('couleur_fond', models.CharField(default='#3498db', help_text='Code couleur hexadécimal', max_length=7)),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage des badges")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Emoji ou nom d'icône", max_length=50)),
                ('couleur', models.CharField(default='#3498db', help_text='Code couleur hexadécimal', max_length=7)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du contenu')),
                ('type_contenu', models.CharField(choices=[('jeu', 'Jeu Interactif'), ('video', 'Vidéo'), ('son', 'Son/Audio'), ('coloriage', 'Coloriage'), ('histoire', 'Histoire'), ('exercice', 'Exercice')], max_length=20)),
                ('niveau_min', models.IntegerField(default=1, help_text='Niveau minimum requis pour accéder à ce contenu')),
                ('niveau_max', models.IntegerField(default=20, help_text='Niveau maximum pour lequel ce contenu est pertinent')),
                ('difficulte', models.IntegerField(choices=[(1, '⭐ Très facile'), (2, '⭐⭐ Facile'), (3, '⭐⭐⭐ Moyen'), (4, '⭐⭐⭐⭐ Difficile'), (5, '⭐⭐⭐⭐⭐ Très difficile')], default=1, help_text='Niveau de difficulté du contenu')),
                ('duree_estimee', models.IntegerField(default=5, help_text='Durée estimée en minutes')),
                ('points_recompense', models.IntegerField(default=20, help_text='Points accordés pour la réussite')),
                ('objectif_pedagogique', models.TextField(blank=True, help_text='Objectif pédagogique du contenu')),
                ('competences_travaillees', models.CharField(blank=True, help_text='Compétences travaillées (séparées par des virgules)', max_length=200)),
                ('fichier', models.FileField(blank=True, help_text='Fichier du contenu (image, audio, vidéo, PDF...)', null=True, upload_to='contenus/%Y/%m/')),
                ('image_preview', models.ImageField(blank=True, help_text='Image de prévisualisation', null=True, upload_to='previews/%Y/%m/')),
                ('url_externe', models.URLField(blank=True, help_text='URL externe si le contenu est hébergé ailleurs')),
                ('fichier_solution', models.FileField(blank=True, help_text='Fichier de solution ou correction (pour les éducateurs)', null=True, upload_to='solutions/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Le contenu est-il visible et accessible ?')),
                ('est_premium', models.BooleanField(default=False, help_text='Réservé aux comptes premium ?')),
                ('est_valide', models.BooleanField(default=False, help_text='Validé par un administrateur ?')),
                ('nombre_vues', models.IntegerField(default=0)),
                ('nombre_completions', models.IntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, help_text='Note moyenne sur 5', max_digits=3)),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules pour faciliter la recherche', max_length=200)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenus', to='progression.categorie')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenus_crees', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenus_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenu éducatif',
                'verbose_name_plural': 'Contenus éducatifs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], help_text='Note de 1 à 5 étoiles')),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='progression.contenu')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation de contenu',
                'verbose_name_plural': 'Évaluations de contenus',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('jeu', 'Jeu'), ('video', 'Vidéo'), ('son', 'Son/Audio'), ('coloriage', 'Coloriage'), ('questionnaire', 'Questionnaire')], max_length=50)),
                ('nom_activite', models.CharField(max_length=200)),
                ('points_gagnes', models.IntegerField(default=0)),
                ('duree_secondes', models.IntegerField(blank=True, help_text="Durée de l'activité en secondes", null=True)),
                ('reussite', models.BooleanField(default=True, help_text="L'activité a-t-elle été réussie ?")),
                ('score_activite', models.IntegerField(blank=True, help_text="Score obtenu dans l'activité (si applicable)", null=True)),
                ('date_activite', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='progression.enfantprogression')),
            ],
            options={
                'verbose_name': "Historique d'activité",
                'verbose_name_plural': "Historiques d'activités",
                'ordering': ['-date_activite'],
            },
        ),
        migrations.CreateModel(
            name='NiveauContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField()),
                ('est_obligatoire', models.BooleanField(default=False, help_text='Ce contenu est-il obligatoire pour ce niveau ?')),
                ('ordre_dans_niveau', models.IntegerField(default=0, help_text='Ordre de présentation dans le niveau')),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_assignes', to='progression.contenu')),
            ],
            options={
                'verbose_name': 'Contenu de niveau',
                'verbose_name_plural': 'Contenus de niveaux',
                'ordering': ['niveau', 'ordre_dans_niveau'],
            },
        ),
        migrations.CreateModel(
            name='BadgeObtenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progression.badge')),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='progression.enfantprogression')),
            ],
            options={
                'verbose_name': 'Badge obtenu',
                'verbose_name_plural': 'Badges obtenus',
                'ordering': ['-date_obtention'],
                'unique_together': {('enfant', 'badge')},
            },
        ),
        migrations.AddIndex(
            model_name='contenu',
            index=models.Index(fields=['type_contenu', 'est_actif'], name='progression_type_co_68a44b_idx'),
        ),
        migrations.AddIndex(
            model_name='contenu',
            index=models.Index(fields=['niveau_min', 'niveau_max'], name='progression_niveau__3810db_idx'),
        ),
        migrations.AddIndex(
            model_name='contenu',
            index=models.Index(fields=['categorie', 'est_actif'], name='progression_categor_03bc38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationcontenu',
            unique_together={('contenu', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='niveaucontenu',
            unique_together={('niveau', 'contenu')},
        ),
    ]
